=== Niharika-1505/100DaysofCoding/ExtraPractice/NHS_ODS_DATA_XSD_XML_To_DATAFRAME/HSCOrgRefData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://refdata.hscic.gov.uk/org/v2-0-0" id="HSCOrgRefData" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://refdata.hscic.gov.uk/org/v2-0-0" xmlns:HSCOrgRefData="http://refdata.hscic.gov.uk/org/v2-0-0">
<!-- Schema version: v2-0-0
Status: Live
Author: HSCIC
Contact: exeter.helpdesk@nhs.net
Release Date: 2017-15-02
Project: HSCOrgRefData
Internal Ref: V1.0
Copyright Health and Social Care Information Centre (c) 2017 -->
	<xs:element name="OrgRefData" type="OrgType">
		<xs:annotation>
			<xs:documentation>This is the root element of the XML document.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="OrgType">
		<xs:annotation>
			<xs:documentation>Container for the Manifest, CodeSystems and Payload.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Manifest" type="OrgManifestType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="CodeSystems" type="CodeSystemsType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Organisations" type="OrgOrganisationsType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrgManifestType">
		<xs:annotation>
			<xs:documentation>Manifest occurs once at the top of the file and describes the content.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Version" type="ValMaxStrLen12" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PublicationType" type="ValMaxStrLen12" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PublicationSource" type="ValMaxStrLen12" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PublicationDate" type="ValDateType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PublicationSeqNum" type="ValMaxStrLen25" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FileCreationDateTime" type="ValTimestampType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FileExpiryDate" type="ValDateType" minOccurs="0" maxOccurs="1" nillable="true"/>
			<xs:element name="RecordCount" type="ValDeciNoFrac" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ContentDescription" type="ValMaxStrLen100" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PrimaryRoleScope" type="PrimaryRoleScopeType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimaryRoleScopeType">
		<xs:annotation>
			<xs:documentation>List of Primary Roles for subject records in this file.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="PrimaryRole" type="PrimaryRoleType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimaryRoleType">
		<xs:annotation>
			<xs:documentation>An entry exists for each Role which is in scope for a given document.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="id" use="required" type="xs:IDREF"/>
		<xs:attribute name="displayName" use="required" type="maxStrLen100"/>
	</xs:complexType>
	<xs:complexType name="CodeSystemsType">
		<xs:annotation>
			<xs:documentation>CodeSystems defined here and referenced from subject records in the payload.</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="CodeSystem" type="CodeSystemType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CodeSystemType">
		<xs:annotation>
			<xs:documentation>Each CodeSystem collection has its own section.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="concept" type="ConceptType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="maxStrLen50"/>
		<xs:attribute name="oid" use="required" type="oidStrLen50"/>
	</xs:complexType>
	<xs:complexType name="ConceptType">
		<xs:annotation>
			<xs:documentation>Each entry is an instance of a particular CodeSystem.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="id" use="required" type="xs:ID"/>
		<xs:attribute name="code" use="required" type="maxStrLen12"/>
		<xs:attribute name="displayName" use="required" type="maxStrLen100"/>
	</xs:complexType>
	<xs:complexType name="OrgOrganisationsType">
		<xs:annotation>
			<xs:documentation>Container for Organisation records in the payload.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Organisation" type="OrgOrganisationType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrgOrganisationType">
		<xs:annotation>
			<xs:documentation>An entry for each Organisation entity in the payload.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Name" type="maxStrLen100" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Date" type="DateIVLValueType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="OrgId" type="II" minOccurs="1" maxOccurs="1"/>
			<xs:element name="OtherId" type="II" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
			<xs:element name="Status" type="ValMaxStrLen12" minOccurs="1" maxOccurs="1"/>
			<xs:element name="LastChangeDate" type="ValDateType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="GeoLoc" type="GeoLocType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Contacts" type="OrgContactsType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Roles" type="OrgRolesType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Rels" type="OrgRelsType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Succs" type="OrgSuccsType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AdditionalAttributes" type="OrgAdditionalAttributesType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="refOnly" use="optional" type="xs:boolean"/>
		<xs:attribute name="orgRecordClass" use="required" type="xs:IDREF"/>
	</xs:complexType>
	<xs:complexType name="OrgRelsType">
		<xs:annotation>
			<xs:documentation>All relations for given entity are held here (optional) but if the container is present, one or more Relationship entries must be present.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Rel" type="OrgRelType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrgRelType">
		<xs:annotation>
			<xs:documentation>Any relationships for an entity are listed here including information about the target entity.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Date" type="DateIVLValueType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="Status" type="ValMaxStrLen12" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Target" type="TargetType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:IDREF"/>
		<xs:attribute name="uniqueRelId" use="optional" type="deciNoFrac"/>
		<xs:attribute name="derived" use="optional" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="TargetType">
		<xs:annotation>
			<xs:documentation>Contains information about the target entity for a given relationship.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="OrgId" type="II" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PrimaryRoleId" type="TargetRoleIDType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TargetRoleIDType">
		<xs:annotation>
			<xs:documentation>The Primary Role of a target entity (may not conform to the list in Primary Role Scope but will comply with those listed in the OrganisationRoles CodeSystemsType).</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="id" use="required" type="xs:IDREF"/>
		<xs:attribute name="uniqueRoleId" use="optional" type="deciNoFrac"/>
	</xs:complexType>
	<xs:complexType name="OrgSuccsType">
		<xs:annotation>
			<xs:documentation>Contains any predecessor and successor organisations.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Succ" type="OrgSuccType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrgSuccType">
		<xs:annotation>
			<xs:documentation>Represents an individual succession for the subject record.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Date" type="DateIVLValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Type" type="maxStrLen12" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Type field will contain values of "Successor" or "Predecessor".</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Target" type="TargetType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="uniqueSuccId" use="required" type="deciNoFrac"/>
		<xs:attribute name="forwardSuccession" use="optional" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="OrgContactsType">
		<xs:annotation>
			<xs:documentation>All contacts for a given entity are held here.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Contact" type="OrgContactType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrgContactType">
		<xs:annotation>
			<xs:documentation>This data type supports the representation of a contact.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="type" use="required" type="maxStrLen12"/>
		<xs:attribute name="value" use="required" type="maxStrLen255"/>
	</xs:complexType>
	<xs:complexType name="OrgRolesType">
		<xs:annotation>
			<xs:documentation>All Roles assigned to an entity are held here.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Role" type="OrgRoleType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrgRoleType">
		<xs:annotation>
			<xs:documentation>Role records held here and one must represent the entity Primary Role.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Date" type="DateIVLValueType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="Status" type="ValMaxStrLen12" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:IDREF"/>
		<xs:attribute name="uniqueRoleId" use="optional" type="deciNoFrac"/>
		<xs:attribute name="primaryRole" use="optional" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="OrgAdditionalAttributesType">
		<xs:annotation>
			<xs:documentation>Additional Attributes linked to a given entity (currently not in scope).</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="AdditionalAttribute" type="AddAttrType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GeoLocType">
		<xs:annotation>
			<xs:documentation>Holds Location information for each Organisation entity, which can be a LocationStringsType element or a LocationId element.</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="LocationId" type="II" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Location" type="LocationStringsType" minOccurs="0" maxOccurs="1"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="LocationStringsType">
		<xs:annotation>
			<xs:documentation>This data type supports the representation location information in strings.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="AddrLn1" type="maxStrLen75" minOccurs="1" maxOccurs="1"/>
			<xs:element name="AddrLn2" type="maxStrLen75" minOccurs="0" maxOccurs="1" nillable="true"/>
			<xs:element name="AddrLn3" type="maxStrLen75" minOccurs="0" maxOccurs="1" nillable="true"/>
			<xs:element name="Town" type="maxStrLen75" minOccurs="0" maxOccurs="1" nillable="true"/>
			<xs:element name="County" type="maxStrLen75" minOccurs="0" maxOccurs="1" nillable="true"/>
			<xs:element name="PostCode" type="maxStrLen15" minOccurs="0" maxOccurs="1" nillable="true"/>
			<xs:element name="Country" type="maxStrLen50" minOccurs="0" maxOccurs="1" nillable="true"/>
			<xs:element name="UPRN" type="deciNoFrac" minOccurs="0" maxOccurs="1" nillable="true"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ANY" abstract="true">
		<xs:annotation>
			<xs:documentation>This data type represents an abstract type from which more specific data types are derived.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
	</xs:complexType>
	<xs:complexType name="ValDateType">
		<xs:annotation>
			<xs:documentation>This data type supports the representation of a date.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ANY">
				<xs:sequence/>
				<xs:attribute name="value" use="optional" type="xs:date"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ValTimestampType">
		<xs:annotation>
			<xs:documentation>This data type supports the representation of a timeStamp.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ANY">
				<xs:sequence/>
				<xs:attribute name="value" use="optional" type="xs:dateTime"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DateIVLValueType">
		<xs:annotation>
			<xs:documentation>This is the custom date type to represent start and end dates for various components of the organisation record.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ANY">
				<xs:sequence>
					<xs:element name="Type" type="ValMaxStrLen12" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Start" type="ValDateType" minOccurs="1" maxOccurs="1"/>
					<xs:element name="End" type="ValDateType" minOccurs="0" maxOccurs="1" nillable="true"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="II">
		<xs:annotation>
			<xs:documentation>This data type supports the representation of an instance identifier.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ANY">
				<xs:sequence/>
				<xs:attribute name="root" use="required" type="oidStrLen50"/>
				<xs:attribute name="extension" use="required" type="maxStrLen12"/>
				<xs:attribute name="assigningAuthorityName" use="required" type="maxStrLen25"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="AddAttrType">
		<xs:annotation>
			<xs:documentation>Container for Additional Attribute records (currently out of scope).</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Key" type="maxStrLen50" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Value" type="maxStrLen255" minOccurs="1" maxOccurs="1"/>
			<xs:element name="AttributeDate" type="ValDateType" minOccurs="0" maxOccurs="1" nillable="true"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ValMaxStrLen12">
		<xs:annotation>
			<xs:documentation>Value attribute to hold strings up to 12 characters in length.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="optional" type="maxStrLen12"/>
	</xs:complexType>
	<xs:complexType name="ValMaxStrLen15">
		<xs:annotation>
			<xs:documentation>Value attribute to hold strings up to 15 characters in length.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="optional" type="maxStrLen15"/>
	</xs:complexType>
	<xs:complexType name="ValMaxStrLen25">
		<xs:annotation>
			<xs:documentation>Value attribute to hold strings up to 25 characters in length.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="optional" type="maxStrLen25"/>
	</xs:complexType>
	<xs:complexType name="ValMaxStrLen50">
		<xs:annotation>
			<xs:documentation>Value attribute to hold strings up to 50 characters in length.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="optional" type="maxStrLen50"/>
	</xs:complexType>
	<xs:complexType name="ValMaxStrLen75">
		<xs:annotation>
			<xs:documentation>Value attribute to hold strings up to 75 characters in length.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="optional" type="maxStrLen75"/>
	</xs:complexType>
	<xs:complexType name="ValMaxStrLen100">
		<xs:annotation>
			<xs:documentation>Value attribute to hold strings up to 100 characters in length.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="optional" type="maxStrLen100"/>
	</xs:complexType>
	<xs:complexType name="ValMaxStrLen255">
		<xs:annotation>
			<xs:documentation>Value attribute to hold strings up to 255 characters in length.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="optional" type="maxStrLen255"/>
	</xs:complexType>
	<xs:complexType name="ValDeciNoFrac">
		<xs:annotation>
			<xs:documentation>Value attribute to hold whole numbers up to 12 digits.</xs:documentation>
		</xs:annotation>
		<xs:sequence/>
		<xs:attribute name="value" use="required" type="deciNoFrac"/>
	</xs:complexType>
	<xs:simpleType name="oidStrLen50">
		<xs:annotation>
			<xs:documentation>This data type supports the representation of an object identifier.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9][0-9]*)(\.[0-9][0-9]*)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxStrLen12">
		<xs:annotation>
			<xs:documentation>Defines a value as a string with a maximum length of 12.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="12"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxStrLen15">
		<xs:annotation>
			<xs:documentation>Defines a value as a string with a maximum length of 15.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="15"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxStrLen25">
		<xs:annotation>
			<xs:documentation>Defines a value as a string with a maximum length of 25.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="25"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxStrLen50">
		<xs:annotation>
			<xs:documentation>Defines a value as a string with a maximum length of 50.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxStrLen75">
		<xs:annotation>
			<xs:documentation>Defines a value as a string with a maximum length of 75.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="75"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxStrLen100">
		<xs:annotation>
			<xs:documentation>Defines a value as a string with a maximum length of 100.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxStrLen255">
		<xs:annotation>
			<xs:documentation>Defines a value as a string with a maximum length of 255.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="deciNoFrac">
		<xs:annotation>
			<xs:documentation>Defines a value as a decimal, where the maximum number of digits permitted is less than or equal to 12, and limits the value to a whole number only (no decimal places).</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="0"/>
			<xs:totalDigits value="12"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Niharika-1505/100DaysofCoding/ExtraPractice/NHS_ODS_DATA_XSD_XML_To_DATAFRAME/Sample_file.xml
<?xml version="1.0" encoding="utf-8"?>
<HSCOrgRefData:OrgRefData xmlns:HSCOrgRefData="http://refdata.hscic.gov.uk/org/v2-0-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://refdata.hscic.gov.uk/org/v2-0-0 HSCOrgRefData.xsd">
  <Manifest>
    <Version value="2-0-0" />
    <PublicationType value="Full" />
    <PublicationSource value="HSCIC" />
    <PublicationDate value="2022-07-25" />
    <PublicationSeqNum value="1755" />
    <FileCreationDateTime value="2022-07-25T22:14:25" />
    <RecordCount value="278411" />
    <ContentDescription value="HSCOrgRefData_Full_20220725" />
    <PrimaryRoleScope>
      <PrimaryRole id="RO180" displayName="PRIMARY CARE TRUST SITE" />
      <PrimaryRole id="RO198" displayName="NHS TRUST SITE" />
      <PrimaryRole id="RO157" displayName="NON-NHS ORGANISATION" />
      <PrimaryRole id="RO181" displayName="PHARMACY HEADQUARTER" />
      <PrimaryRole id="RO191" displayName="SPECIAL HEALTH AUTHORITY SITE" />
      <PrimaryRole id="RO96" displayName="BRANCH SURGERY" />
      <PrimaryRole id="RO108" displayName="CARE TRUST SITE" />
      <PrimaryRole id="RO175" displayName="PRISON" />
      <PrimaryRole id="RO107" displayName="CARE TRUST" />
      <PrimaryRole id="RO176" displayName="INDEPENDENT SECTOR H/C PROVIDER SITE" />
      <PrimaryRole id="RO122" displayName="LOCAL AUTHORITY SITE - LEGACY" />
      <PrimaryRole id="RO197" displayName="NHS TRUST" />
      <PrimaryRole id="RO173" displayName="PATHOLOGY LAB" />
      <PrimaryRole id="RO179" displayName="PRIMARY CARE TRUST" />
      <PrimaryRole id="RO167" displayName="OPTICAL SITE" />
      <PrimaryRole id="RO126" displayName="GOVERNMENT DEPARTMENT" />
      <PrimaryRole id="RO177" displayName="PRESCRIBING COST CENTRE" />
      <PrimaryRole id="RO166" displayName="OPTICAL HEADQUARTERS" />
      <PrimaryRole id="RO161" displayName="NHS SUPPORT AGENCY" />
      <PrimaryRole id="RO141" displayName="LOCAL AUTHORITY" />
      <PrimaryRole id="RO200" displayName="WELSH ASSEMBLY" />
      <PrimaryRole id="RO123" displayName="LOCAL AUTHORITY DEPARTMENT" />
      <PrimaryRole id="RO172" displayName="INDEPENDENT SECTOR HEALTHCARE PROVIDER" />
      <PrimaryRole id="RO142" displayName="LOCAL HEALTH BOARD" />
      <PrimaryRole id="RO146" displayName="LOCAL SERVICE PROVIDER (LSP)" />
      <PrimaryRole id="RO137" displayName="ISLE OF MAN GOVERNMENT DIRECTORATE" />
      <PrimaryRole id="RO140" displayName="ISLE OF MAN GOVERNMENT DIRECTORATE SITE" />
      <PrimaryRole id="RO148" displayName="LOCAL HEALTH BOARD SITE" />
      <PrimaryRole id="RO150" displayName="MILITARY HOSPITAL" />
      <PrimaryRole id="RO93" displayName="APPLICATION SERVICE PROVIDER - LEGACY" />
      <PrimaryRole id="RO110" displayName="GENERAL DENTAL PRACTICE" />
      <PrimaryRole id="RO105" displayName="CANCER REGISTRY" />
      <PrimaryRole id="RO128" displayName="GOVERNMENT OFFICE REGION" />
      <PrimaryRole id="RO189" displayName="SPECIAL HEALTH AUTHORITY (SPHA)" />
      <PrimaryRole id="RO92" displayName="APPLICATION SERVICE PROVIDER" />
      <PrimaryRole id="RO117" displayName="EDUCATION" />
      <PrimaryRole id="RO119" displayName="LOCAL AUTHORITY - LEGACY" />
      <PrimaryRole id="RO132" displayName="HEALTH AUTHORITY (HA)" />
      <PrimaryRole id="RO138" displayName="ISLE OF MAN GOVERNMENT DEPARTMENT" />
      <PrimaryRole id="RO91" displayName="EXECUTIVE AGENCY PROGRAMME" />
      <PrimaryRole id="RO134" displayName="HEALTH OBSERVATORY" />
      <PrimaryRole id="RO158" displayName="NON STATUTORY NHS ORGANISATION" />
      <PrimaryRole id="RO159" displayName="NATIONAL APPLICATION SERVICE PROVIDER" />
      <PrimaryRole id="RO89" displayName="EXECUTIVE AGENCY PROGRAMME - DEPARTMENT" />
      <PrimaryRole id="RO131" displayName="GOVERNMENT DEPARTMENT SITE" />
      <PrimaryRole id="RO147" displayName="LSP SITE" />
      <PrimaryRole id="RO116" displayName="EXECUTIVE AGENCY" />
      <PrimaryRole id="RO154" displayName="NORTHERN IRELAND HEALTH AND SOCIAL CARE TRUST" />
      <PrimaryRole id="RO162" displayName="OTHER STATUTORY AUTHORITY (OSA)" />
      <PrimaryRole id="RO103" displayName="CANCER NETWORK" />
      <PrimaryRole id="RO102" displayName="CLINICAL NETWORK" />
      <PrimaryRole id="RO185" displayName="REGIONAL OFFICE (RO)" />
      <PrimaryRole id="RO153" displayName="NORTHERN IRELAND HEALTH &amp; SOCIAL CARE BOARD" />
      <PrimaryRole id="RO90" displayName="EXECUTIVE AGENCY SITE" />
      <PrimaryRole id="RO136" displayName="STRATEGIC HEALTH AUTHORITY SITE" />
      <PrimaryRole id="RO155" displayName="NORTHERN IRELAND LOCAL COMMISSIONING GROUP" />
      <PrimaryRole id="RO98" displayName="CLINICAL COMMISSIONING GROUP" />
      <PrimaryRole id="RO168" displayName="OTHER STATUTORY AUTHORITY SITE" />
      <PrimaryRole id="RO210" displayName="NHS ENGLAND (REGION, LOCAL OFFICE)" />
      <PrimaryRole id="RO209" displayName="NHS ENGLAND (REGION)" />
      <PrimaryRole id="RO213" displayName="COMMISSIONING SUPPORT UNIT" />
      <PrimaryRole id="RO99" displayName="CLINICAL COMMISSIONING GROUP SITE" />
      <PrimaryRole id="RO214" displayName="COMMISSIONING SUPPORT UNIT SITE" />
      <PrimaryRole id="RO216" displayName="DATA SERVICES FOR COMMISSIONERS REGIONAL OFFICE (DSCRO)" />
      <PrimaryRole id="RO222" displayName="LOCAL AUTHORITY SITE" />
      <PrimaryRole id="RO212" displayName="NHS ENGLAND (REGION, LOCAL OFFICE) SITE" />
      <PrimaryRole id="RO217" displayName="DSCRO SITE" />
      <PrimaryRole id="RO230" displayName="SECURE TRAINING CENTRE" />
      <PrimaryRole id="RO231" displayName="SECURE CHILDREN'S HOME" />
      <PrimaryRole id="RO235" displayName="COURT" />
      <PrimaryRole id="RO234" displayName="POLICE CUSTODY SUITE" />
      <PrimaryRole id="RO233" displayName="CONSTABULARY" />
      <PrimaryRole id="RO228" displayName="YOUNG OFFENDER INSTITUTION" />
      <PrimaryRole id="RO232" displayName="IMMIGRATION REMOVAL CENTRE" />
      <PrimaryRole id="RO182" displayName="PHARMACY" />
      <PrimaryRole id="RO104" displayName="SOCIAL CARE PROVIDER" />
      <PrimaryRole id="RO101" displayName="SOCIAL CARE SITE" />
      <PrimaryRole id="RO94" displayName="APPLIANCE CONTRACTOR" />
      <PrimaryRole id="RO236" displayName="SEXUAL ASSAULT REFERRAL CENTRE" />
      <PrimaryRole id="RO261" displayName="STRATEGIC PARTNERSHIP" />
      <PrimaryRole id="RO272" displayName="PRIMARY CARE NETWORK" />
      <PrimaryRole id="RO280" displayName="PHARMACY SITE" />
      <PrimaryRole id="RO221" displayName="SCHOOL" />
      <PrimaryRole id="RO315" displayName="NORTHERN IRELAND GP PRACTICE" />
    </PrimaryRoleScope>
  </Manifest>
  <CodeSystems>
    <CodeSystem name="OrganisationRecordClass" oid="2.16.840.1.113883.2.1.3.2.4.23">
      <concept id="RC2" code="2" displayName="HSCSite" />
      <concept id="RC1" code="1" displayName="HSCOrg" />
    </CodeSystem>
    <CodeSystem name="OrganisationRole" oid="2.16.840.1.113883.2.1.3.2.4.17.507">
      <concept id="RO179" code="179" displayName="PRIMARY CARE TRUST" />
      <concept id="RO180" code="180" displayName="PRIMARY CARE TRUST SITE" />
      <concept id="RO197" code="197" displayName="NHS TRUST" />
      <concept id="RO198" code="198" displayName="NHS TRUST SITE" />
      <concept id="RO114" code="114" displayName="DMU SITE" />
      <concept id="RO132" code="132" displayName="HEALTH AUTHORITY (HA)" />
      <concept id="RO210" code="210" displayName="NHS ENGLAND (REGION, LOCAL OFFICE)" />
      <concept id="RO261" code="261" displayName="STRATEGIC PARTNERSHIP" />
      <concept id="RO157" code="157" displayName="NON-NHS ORGANISATION" />
      <concept id="RO15" code="15" displayName="REG'D UNDER PART 2 CARE STDS ACT 2000" />
      <concept id="RO7" code="7" displayName="HOSPICE" />
      <concept id="RO181" code="181" displayName="PHARMACY HEADQUARTER" />
      <concept id="RO189" code="189" displayName="SPECIAL HEALTH AUTHORITY (SPHA)" />
      <concept id="RO191" code="191" displayName="SPECIAL HEALTH AUTHORITY SITE" />
      <concept id="RO177" code="177" displayName="PRESCRIBING COST CENTRE" />
      <concept id="RO96" code="96" displayName="BRANCH SURGERY" />
      <concept id="RO107" code="107" displayName="CARE TRUST" />
      <concept id="RO108" code="108" displayName="CARE TRUST SITE" />
      <concept id="RO175" code="175" displayName="PRISON" />
      <concept id="RO24" code="24" displayName="NHS TRUST DERIVED" />
      <concept id="RO57" code="57" displayName="FOUNDATION TRUST" />
      <concept id="RO172" code="172" displayName="INDEPENDENT SECTOR HEALTHCARE PROVIDER" />
      <concept id="RO176" code="176" displayName="INDEPENDENT SECTOR H/C PROVIDER SITE" />
      <concept id="RO119" code="119" displayName="LOCAL AUTHORITY - LEGACY" />
      <concept id="RO122" code="122" displayName="LOCAL AUTHORITY SITE - LEGACY" />
      <concept id="RO142" code="142" displayName="LOCAL HEALTH BOARD" />
      <concept id="RO144" code="144" displayName="WELSH LOCAL HEALTH BOARD" />
      <concept id="RO173" code="173" displayName="PATHOLOGY LAB" />
      <concept id="RO31" code="31" displayName="PPA EPACT SYSTEM" />
      <concept id="RO29" code="29" displayName="TREATMENT CENTRE" />
      <concept id="RO268" code="268" displayName="MEDICINE SUPPLIER" />
      <concept id="RO22" code="22" displayName="LEVEL 04 PCT" />
      <concept id="RO166" code="166" displayName="OPTICAL HEADQUARTERS" />
      <concept id="RO167" code="167" displayName="OPTICAL SITE" />
      <concept id="RO126" code="126" displayName="GOVERNMENT DEPARTMENT" />
      <concept id="RO171" code="171" displayName="PRIMARY CARE GROUP" />
      <concept id="RO98" code="98" displayName="CLINICAL COMMISSIONING GROUP" />
      <concept id="RO272" code="272" displayName="PRIMARY CARE NETWORK" />
      <concept id="RO76" code="76" displayName="GP PRACTICE" />
      <concept id="RO109" code="109" displayName="DISTRICT HEALTH AUTHORITY (DHA)" />
